#!/bin/bash
echo $(( $(echo "$WATER" | tr 'ewatr' 01234 | awk '{n=0; for(i=1;i<=length;i++) n=n*5+substr($0,i,1); print n}') + $(echo "$STIR" | tr 'ti.r' 0123 | awk '{n=0; for(i=1;i<=length;i++) n=n*4+substr($0,i,1); print n}') )) | tr '012345678' 'shtbeolhc'

